/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
<<<<<<< HEAD
 * Generated at: 2016-08-25 08:36:51 UTC
=======
<<<<<<< HEAD
 * Generated at: 2016-08-23 08:10:41 UTC
=======
 * Generated at: 2016-08-23 08:06:46 UTC
>>>>>>> 227933e90cea7fdb00258db62bbd7f6916628cb1
>>>>>>> 8521074db796575873dd59a426f406561b1b8fbc
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script src=\"https://code.jquery.com/jquery-3.1.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.1.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/modernizr.custom.min.js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/jquery-ui-1.10.3.custom.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"content\">\t\t\r\n");
      out.write("\t<div class=\"slideshow\">\r\n");
      out.write("\t    <div class=\"slideshow-slides\">\r\n");
      out.write("\t        <a href=\"\" class=\"slide\" id=\"slide-1\"><img src=\"./images/slide-1.jpg\" alt=\"\"></a>\r\n");
      out.write("\t        <a href=\"\" class=\"slide\" id=\"slide-2\"><img src=\"./images/slide-2.jpg\" alt=\"\"></a>\r\n");
      out.write("\t        <a href=\"\" class=\"slide\" id=\"slide-3\"><img src=\"./images/slide-3.jpg\" alt=\"\"></a>\r\n");
      out.write("\t        <a href=\"\" class=\"slide\" id=\"slide-4\"><img src=\"./images/slide-4.jpg\" alt=\"\"></a>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"slideshow-nav\">\r\n");
      out.write("\t        <a href=\"\" class=\"prev\">Prev</a>\r\n");
      out.write("\t        <a href=\"\" class=\"next\">Next</a>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"slideshow-indicator\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"board-table\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col width=\"80%\" />\r\n");
      out.write("\t\t\t<col width=\"20%\" />\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th><span class=\"icon-notice\"></span>공지사항</th>\t\t\r\n");
      out.write("\t\t\t\t<th><a href=\"javascript:void(0)\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/notice/noticeList.htm'\">></a></th>\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"ellipsis\">최근공지사항최근공지사항최근공지사항최근공지사항최근공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항</td>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: center;\"><strong>2016.08.19</strong></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"ellipsis\">최근공지사항최근공지사항최근공지사항최근공지사항최근공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항</td>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: center;\"><strong>2016.08.19</strong></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"board-table\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col width=\"80%\" />\r\n");
      out.write("\t\t\t<col width=\"20%\" />\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th><span class=\"icon-notice\"></span>최근 게시물</th>\t\r\n");
      out.write("\t\t\t\t<th></th>\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"ellipsis\">최근공지사항최근공지사항최근공지사항최근공지사항최근공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항</td>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: center;\"><strong>2016.08.19</strong></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"ellipsis\">최근공지사항최근공지사항최근공지사항최근공지사항최근공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항공지사항최근공지사항</td>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: center;\"><strong>2016.08.19</strong></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
